// Enterprise ERP — Standard Sequence Document Catalog
// Master Data Registry defining WHAT document types can undergo document sequencing
// Source: Screenshots 1, 2, 4 + Core Orminal ERP Module Architecture

export interface StandardDocTypeItem {
  code: string // Business / Display Code (e.g. "1", "2", "35", "58")
  docTypeKey: string // Immutable System Identity (e.g. "sales_invoice", "journal_entry")
  nameAr: string // Display Name (Arabic)
  nameEn: string // Display Name (English)
  moduleCode: 'FIN' | 'SAL' | 'PUR' | 'INV' | 'POS' | 'HR' | 'MFG' | 'AST' | 'SYS'
  mainDocType: 'financial' | 'sales' | 'purchases' | 'inventory' | 'pos' | 'payroll' | 'manufacturing' | 'assets' | 'system'
  affectsFinancial: boolean // Metadata / Capability indicator
  affectsInventory: boolean // Metadata / Capability indicator
  postingProfileCode?: string // Semantic link to posting profile
  requiresApproval?: boolean // Workflow indicator
  sortOrder: number
  notes?: string
}

export const STANDARD_SEQUENCE_DOC_TYPES_VERSION = '1.0.0'

export const STANDARD_SEQUENCE_DOC_TYPES: StandardDocTypeItem[] = [
  // === Financial & Accounts (الحسابات والمالية) ===
  {
    code: '1',
    docTypeKey: 'debit_note',
    nameAr: 'إشعار مدين',
    nameEn: 'Debit Note',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'DEBIT_NOTE',
    requiresApproval: true,
    sortOrder: 1,
  },
  {
    code: '2',
    docTypeKey: 'sales_credit_note',
    nameAr: 'إشعار دائن',
    nameEn: 'Credit Note',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'CREDIT_NOTE',
    requiresApproval: true,
    sortOrder: 2,
  },
  {
    code: '3',
    docTypeKey: 'journal_entry',
    nameAr: 'قيد يوميه',
    nameEn: 'Journal Entry',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'JOURNAL_ENTRY',
    requiresApproval: true,
    sortOrder: 3,
  },
  {
    code: '4',
    docTypeKey: 'sales_payment',
    nameAr: 'سند قبض',
    nameEn: 'Receipt Voucher',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'RECEIPT_VOUCHER',
    requiresApproval: false,
    sortOrder: 4,
  },
  {
    code: '5',
    docTypeKey: 'purchase_payment',
    nameAr: 'سند صرف',
    nameEn: 'Payment Voucher',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'PAYMENT_VOUCHER',
    requiresApproval: true,
    sortOrder: 5,
  },
  {
    code: '6',
    docTypeKey: 'cash_count',
    nameAr: 'جرد النقدية',
    nameEn: 'Cash Reconciliation',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'CASH_COUNT',
    requiresApproval: true,
    sortOrder: 6,
  },
  {
    code: '7',
    docTypeKey: 'check_receipt',
    nameAr: 'إدارة الشيكات قبض',
    nameEn: 'Incoming Checks Management',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'CHECK_RECEIPT',
    requiresApproval: false,
    sortOrder: 7,
  },
  {
    code: '8',
    docTypeKey: 'check_payment',
    nameAr: 'إدارة الشيكات صرف',
    nameEn: 'Outgoing Checks Management',
    moduleCode: 'FIN',
    mainDocType: 'financial',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'CHECK_PAYMENT',
    requiresApproval: true,
    sortOrder: 8,
  },

  // === Inventory & Warehouses (المخازن والمستودعات) ===
  {
    code: '9',
    docTypeKey: 'delivery',
    nameAr: 'Bill Outgoing Order',
    nameEn: 'Bill Outgoing Order',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'DELIVERY_NOTE',
    requiresApproval: false,
    sortOrder: 9,
  },
  {
    code: '10',
    docTypeKey: 'return_receipt',
    nameAr: 'Incoming Ret. Order',
    nameEn: 'Incoming Return Order',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'RETURN_RECEIPT',
    requiresApproval: true,
    sortOrder: 10,
  },
  {
    code: '16',
    docTypeKey: 'stock_transfer',
    nameAr: 'أمر التحويل المخزني',
    nameEn: 'Stock Transfer Order',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: false,
    affectsInventory: true,
    postingProfileCode: 'STOCK_TRANSFER',
    requiresApproval: true,
    sortOrder: 16,
  },
  {
    code: '17',
    docTypeKey: 'goods_receipt',
    nameAr: 'أمر الإستلام المخزني',
    nameEn: 'Goods Receipt Order',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'GOODS_RECEIPT',
    requiresApproval: false,
    sortOrder: 17,
  },
  {
    code: '18',
    docTypeKey: 'stock_return',
    nameAr: 'مرتجع أمر المخزني',
    nameEn: 'Warehouse Return Order',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'STOCK_RETURN',
    requiresApproval: true,
    sortOrder: 18,
  },
  {
    code: '19',
    docTypeKey: 'stock_take',
    nameAr: 'الجرد المخزني',
    nameEn: 'Physical Stocktaking',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'STOCK_ADJUSTMENT',
    requiresApproval: true,
    sortOrder: 19,
  },
  {
    code: '21',
    docTypeKey: 'purchase_order',
    nameAr: 'أمر الشراء',
    nameEn: 'Purchase Order',
    moduleCode: 'PUR',
    mainDocType: 'purchases',
    affectsFinancial: false,
    affectsInventory: false,
    requiresApproval: true,
    sortOrder: 21,
  },
  {
    code: '22',
    docTypeKey: 'auto_stocktake',
    nameAr: 'Auto stocktaking',
    nameEn: 'Auto Stocktaking',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    requiresApproval: true,
    sortOrder: 22,
  },
  {
    code: '24',
    docTypeKey: 'purchase_invoice',
    nameAr: 'فاتوره المشتريات',
    nameEn: 'Purchase Invoice',
    moduleCode: 'PUR',
    mainDocType: 'purchases',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'PURCHASE_INVOICE',
    requiresApproval: true,
    sortOrder: 24,
  },
  {
    code: '25',
    docTypeKey: 'purchase_credit_note',
    nameAr: 'فاتورة مردود المشتريات',
    nameEn: 'Purchase Return Invoice',
    moduleCode: 'PUR',
    mainDocType: 'purchases',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'PURCHASE_RETURN',
    requiresApproval: true,
    sortOrder: 25,
  },

  // === POS (نقاط البيع) ===
  {
    code: '30',
    docTypeKey: 'pos_invoice',
    nameAr: 'فاتورة نقاط البيع',
    nameEn: 'POS Invoice',
    moduleCode: 'POS',
    mainDocType: 'pos',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'POS_INVOICE',
    requiresApproval: false,
    sortOrder: 30,
  },
  {
    code: '31',
    docTypeKey: 'pos_return',
    nameAr: 'فاتورة مردود نقاط البيع',
    nameEn: 'POS Return Invoice',
    moduleCode: 'POS',
    mainDocType: 'pos',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'POS_RETURN',
    requiresApproval: false,
    sortOrder: 31,
  },

  // === Sales (المبيعات) ===
  {
    code: '35',
    docTypeKey: 'sales_invoice',
    nameAr: 'فاتورة المبيعات',
    nameEn: 'Sales Invoice',
    moduleCode: 'SAL',
    mainDocType: 'sales',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'SALES_INVOICE',
    requiresApproval: false,
    sortOrder: 35,
  },
  {
    code: '36',
    docTypeKey: 'sales_return',
    nameAr: 'فاتورة مردود مبيعات',
    nameEn: 'Sales Return Invoice',
    moduleCode: 'SAL',
    mainDocType: 'sales',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'SALES_RETURN',
    requiresApproval: true,
    sortOrder: 36,
  },

  // === Extended POS Ops ===
  {
    code: '50',
    docTypeKey: 'pos_order',
    nameAr: 'فاتورة نقاط البيع - طلب',
    nameEn: 'POS Order',
    moduleCode: 'POS',
    mainDocType: 'pos',
    affectsFinancial: true,
    affectsInventory: true,
    sortOrder: 50,
  },
  {
    code: '51',
    docTypeKey: 'pos_refund',
    nameAr: 'مردود نقاط البيع',
    nameEn: 'POS Refund',
    moduleCode: 'POS',
    mainDocType: 'pos',
    affectsFinancial: true,
    affectsInventory: true,
    sortOrder: 51,
  },
  {
    code: '53',
    docTypeKey: 'pos_cash_in',
    nameAr: 'قبض نقدي نقطة بيع',
    nameEn: 'POS Cash In',
    moduleCode: 'POS',
    mainDocType: 'pos',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 53,
  },
  {
    code: '54',
    docTypeKey: 'pos_cash_out',
    nameAr: 'صرف نقدي نقطة بيع',
    nameEn: 'POS Cash Out',
    moduleCode: 'POS',
    mainDocType: 'pos',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 54,
  },
  {
    code: '55',
    docTypeKey: 'pos_settlement',
    nameAr: 'تصفية نقاط البيع',
    nameEn: 'POS Shift Settlement',
    moduleCode: 'POS',
    mainDocType: 'pos',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 55,
  },

  // === Extended Inventory Ops ===
  {
    code: '56',
    docTypeKey: 'inventory_outgoing',
    nameAr: 'أمر الصرف المخزني',
    nameEn: 'Inventory Outgoing Order',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    sortOrder: 56,
  },
  {
    code: '57',
    docTypeKey: 'item_replacement',
    nameAr: 'إستبدال',
    nameEn: 'Item Replacement',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: false,
    affectsInventory: true,
    sortOrder: 57,
  },
  {
    code: '58',
    docTypeKey: 'inventory_incoming',
    nameAr: 'أمر توريد مخزني',
    nameEn: 'Inventory Inward Order',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    sortOrder: 58,
  },

  // === HR & Payroll (الموارد البشرية والرواتب) ===
  {
    code: '62',
    docTypeKey: 'hr_recurring_elements',
    nameAr: 'إسناد البنود الدائمة',
    nameEn: 'Recurring Payroll Elements',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 62,
  },
  {
    code: '63',
    docTypeKey: 'hr_variable_elements',
    nameAr: 'إسناد البنود المتغيرة',
    nameEn: 'Variable Payroll Elements',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 63,
  },
  {
    code: '64',
    docTypeKey: 'sales_quotation',
    nameAr: 'عروض الأسعار',
    nameEn: 'Sales Quotation',
    moduleCode: 'SAL',
    mainDocType: 'sales',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 64,
  },
  {
    code: '65',
    docTypeKey: 'sales_order',
    nameAr: 'طلب العميل',
    nameEn: 'Sales Order / Customer Order',
    moduleCode: 'SAL',
    mainDocType: 'sales',
    affectsFinancial: false,
    affectsInventory: false,
    requiresApproval: true,
    sortOrder: 65,
  },
  {
    code: '66',
    docTypeKey: 'hr_benefit_disbursement',
    nameAr: 'صرف المستحقات',
    nameEn: 'Benefit Disbursement',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 66,
  },
  {
    code: '67',
    docTypeKey: 'hr_end_of_service',
    nameAr: 'نهاية الخدمة',
    nameEn: 'End of Service Settlement',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: true,
    affectsInventory: false,
    requiresApproval: true,
    sortOrder: 67,
  },
  {
    code: '68',
    docTypeKey: 'payslip',
    nameAr: 'احتساب الراتب',
    nameEn: 'Payroll Run / Payslip',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'PAYROLL',
    requiresApproval: true,
    sortOrder: 68,
  },
  {
    code: '69',
    docTypeKey: 'hr_leave_settlement',
    nameAr: 'Leave Settlement',
    nameEn: 'Leave Settlement',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 69,
  },
  {
    code: '70',
    docTypeKey: 'hr_leave_grant',
    nameAr: 'Leave Grant',
    nameEn: 'Leave Grant',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 70,
  },
  {
    code: '71',
    docTypeKey: 'hr_task',
    nameAr: 'Task',
    nameEn: 'Task Assignment',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 71,
  },
  {
    code: '72',
    docTypeKey: 'hr_permission',
    nameAr: 'Permission',
    nameEn: 'Permission Request',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 72,
  },
  {
    code: '73',
    docTypeKey: 'hr_departure',
    nameAr: 'Departure Calculation',
    nameEn: 'Departure Calculation',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 73,
  },
  {
    code: '74',
    docTypeKey: 'hr_loan_grant',
    nameAr: 'Loan Grant',
    nameEn: 'Loan Grant',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 74,
  },
  {
    code: '75',
    docTypeKey: 'hr_loan_settlement',
    nameAr: 'Loan Settlement',
    nameEn: 'Loan Settlement',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: true,
    affectsInventory: false,
    sortOrder: 75,
  },
  {
    code: '78',
    docTypeKey: 'hr_work_resumption',
    nameAr: 'Direct Work',
    nameEn: 'Direct Work / Resumption',
    moduleCode: 'HR',
    mainDocType: 'payroll',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 78,
  },

  // === Manufacturing & Fixed Assets (التصنيع والأصول) ===
  {
    code: '40',
    docTypeKey: 'production_order',
    nameAr: 'أمر الإنتاج',
    nameEn: 'Production Order',
    moduleCode: 'MFG',
    mainDocType: 'manufacturing',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'PRODUCTION_ORDER',
    requiresApproval: true,
    sortOrder: 40,
  },
  {
    code: '41',
    docTypeKey: 'bom',
    nameAr: 'قائمة المواد BOM',
    nameEn: 'Bill of Materials',
    moduleCode: 'MFG',
    mainDocType: 'manufacturing',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 41,
  },
  {
    code: '45',
    docTypeKey: 'asset_depreciation',
    nameAr: 'إهلاك الأصول',
    nameEn: 'Asset Depreciation',
    moduleCode: 'AST',
    mainDocType: 'assets',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'DEPRECIATION',
    sortOrder: 45,
  },
  {
    code: '46',
    docTypeKey: 'asset_disposal',
    nameAr: 'استبعاد الأصول',
    nameEn: 'Asset Disposal',
    moduleCode: 'AST',
    mainDocType: 'assets',
    affectsFinancial: true,
    affectsInventory: false,
    postingProfileCode: 'ASSET_DISPOSAL',
    sortOrder: 46,
  },
  {
    code: '15',
    docTypeKey: 'purchase_request',
    nameAr: 'طلب شراء',
    nameEn: 'Purchase Request',
    moduleCode: 'PUR',
    mainDocType: 'purchases',
    affectsFinancial: false,
    affectsInventory: false,
    requiresApproval: true,
    sortOrder: 15,
  },
  {
    code: '14',
    docTypeKey: 'rfq',
    nameAr: 'طلب عرض سعر من مورد',
    nameEn: 'Request for Quotation',
    moduleCode: 'PUR',
    mainDocType: 'purchases',
    affectsFinancial: false,
    affectsInventory: false,
    sortOrder: 14,
  },
  {
    code: '26',
    docTypeKey: 'inventory_adjustment',
    nameAr: 'تسوية مخزنية',
    nameEn: 'Inventory Adjustment',
    moduleCode: 'INV',
    mainDocType: 'inventory',
    affectsFinancial: true,
    affectsInventory: true,
    postingProfileCode: 'STOCK_ADJUSTMENT',
    requiresApproval: true,
    sortOrder: 26,
  },
]
